"""Hermes backtesting web UI (Streamlit). Launch with ``hermes-ui``.

Runs a strategy's Backtest in-process and shows the equity curve, metrics, trades, and a
Claude Code–driven review (ADR-0008). Run as a script by Streamlit, so imports are
absolute.
"""

from __future__ import annotations

from datetime import UTC, datetime, time

import plotly.graph_objects as go
import streamlit as st

from hermes.webui import discovery, review, sources, universes

st.set_page_config(page_title="Hermes Backtester", layout="wide")
st.title("Hermes — backtesting")

_SINGLE = "— single symbol —"


def _fmt_pct(x):
    return "—" if x is None else f"{x * 100:.2f}%"


def _fmt_num(x):
    return "—" if x is None else f"{x:.2f}"


def _param_widget(spec):
    """Render an editable control for a declared strategy Parameter; return its value."""
    label = spec.description or spec.name
    key = f"p_{spec.name}"
    if spec.choices:
        default = spec.default if spec.default in spec.choices else spec.choices[0]
        return st.selectbox(label, list(spec.choices), index=list(spec.choices).index(default), key=key)
    if isinstance(spec.default, bool):
        return st.checkbox(label, value=spec.default, key=key)
    cast = int if isinstance(spec.default, int) else float
    kw = {}
    if spec.bounds:
        kw["min_value"], kw["max_value"] = cast(spec.bounds[0]), cast(spec.bounds[1])
    if isinstance(spec.default, int):
        return int(st.number_input(label, value=spec.default, step=1, key=key, **kw))
    if isinstance(spec.default, float):
        return float(st.number_input(label, value=float(spec.default), key=key, **kw))
    return st.text_input(label, value=str(spec.default), key=key)


def _equity_figure(result):
    ts = [t for t, _ in result.equity_curve]
    eq = [e for _, e in result.equity_curve]
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=ts, y=eq, name="Equity", line=dict(color="#2563eb")))
    fig.update_layout(
        height=420,
        margin=dict(l=0, r=0, t=10, b=0),
        yaxis=dict(title="Equity"),
        showlegend=False,
    )
    return fig


# --- pick a strategy -------------------------------------------------------

entries = discovery.discover()
if not entries:
    st.info(
        "No strategies found in `strategies/`. Create one with the **`/hermes-strategy`** "
        "skill in Claude Code, then reload."
    )
    st.stop()

names = [e.name for e in entries]
choice = st.selectbox("Strategy", names)
entry = next(e for e in entries if e.name == choice)
if entry.is_ai_generated:
    st.caption("🤖 AI-generated by hermes-strategy.")

# --- config form (pre-filled from the strategy's defaults) -----------------

defaults = discovery.default_config(entry)
param_specs = discovery.declared_parameters(entry)
src_names = sources.source_names()
with st.form("run"):
    c1, c2, c3 = st.columns(3)
    source_name = c1.selectbox(
        "Source",
        src_names,
        index=src_names.index(defaults.source.name) if defaults.source.name in src_names else 0,
        help="Data provider for the symbol. cTrader/Pepperstone needs CTRADER_* env credentials.",
    )
    universe = c1.selectbox(
        "Symbols",
        [_SINGLE, *universes.universe_names()],
        help="Run one symbol (typed below) or a whole ticker list from tickers/*.json.",
    )
    ticker = c1.text_input("Symbol", value=defaults.symbol.ticker, help=f"Used when Symbols = {_SINGLE}.")
    cash = c1.number_input("Starting cash", value=float(defaults.starting_cash), step=1000.0)
    start = c2.date_input("Start", value=defaults.start.date())
    end = c3.date_input("End", value=defaults.end.date())
    st.caption(f"Timeframes: {', '.join(str(tf) for tf in defaults.timeframes)}")
    if source_name in sources.NEEDS_SETUP:
        st.caption("⚠️ cTrader/Pepperstone needs `CTRADER_*` credentials and its live fetch wired.")

    param_values: dict = {}
    if param_specs:
        st.markdown("**Parameters**")
        pcols = st.columns(min(len(param_specs), 3))
        for i, spec in enumerate(param_specs):
            with pcols[i % len(pcols)]:
                param_values[spec.name] = _param_widget(spec)

    run = st.form_submit_button("Run backtest", type="primary")

if run:
    start_dt = datetime.combine(start, time(), tzinfo=UTC)
    end_dt = datetime.combine(end, time(), tzinfo=UTC)
    if universe == _SINGLE:
        bt = discovery.configured_backtest(
            entry, source_name=source_name, ticker=ticker,
            start=start_dt, end=end_dt, starting_cash=cash, params=param_values,
        )
        try:
            with st.spinner("Running backtest… (first run may fetch data)"):
                result = bt.run()
        except Exception as exc:  # surface fetch/provider errors cleanly, not a traceback
            st.error(f"Backtest failed on source `{source_name}` / `{ticker}`: {exc}")
            st.stop()
        rid = review.run_id(result.to_dict())
        review.write_result(result.to_dict(), rid)
        review.save_last_rid(rid)
        st.session_state.update(result=result, rid=rid, ai=entry.is_ai_generated, mode="single")
        st.session_state.pop("batch", None)
    else:
        src_override, tickers = universes.load_universe(universe)
        bar = st.progress(0.0, f"Running {universe} ({len(tickers)} symbols)…")
        batch = discovery.run_universe(
            entry, tickers=tickers, source_name=src_override or source_name,
            start=start_dt, end=end_dt, starting_cash=cash, params=param_values,
            progress=lambda done, total: bar.progress(done / max(total, 1), f"Backtesting {done}/{total}…"),
        )
        bar.empty()
        st.session_state.update(batch=batch, mode="batch")
        st.session_state.pop("result", None)

# --- results ---------------------------------------------------------------

mode = st.session_state.get("mode")
batch = st.session_state.get("batch")
result = None

if mode == "batch" and batch is not None:
    agg = batch.aggregate()
    st.subheader("Universe scan — by symbol")
    a = st.columns(5)
    a[0].metric("Symbols", agg["symbols"])
    a[1].metric("Mean return / symbol", _fmt_pct(agg["mean_return"]))
    a[2].metric("Median Sharpe", _fmt_num(agg["median_sharpe"]))
    a[3].metric("% profitable", _fmt_pct(agg["pct_profitable"]))
    a[4].metric("Total trades", agg["total_trades"])
    st.dataframe(batch.summary_rows(), use_container_width=True, hide_index=True)
    if batch.errors:
        with st.expander(f"⚠️ {len(batch.errors)} symbol(s) failed"):
            for t, e in batch.errors.items():
                st.write(f"**{t}** — {e}")
    if not batch.results:
        st.stop()

    st.divider()
    view = st.selectbox("Equity curve, metrics & review for", ["Combined portfolio", *batch.results])
    if view == "Combined portfolio":
        result = batch.combined_result()
        st.caption("The basket as one portfolio — equal capital per symbol, run independently and summed.")
    else:
        result = batch.results[view]
    rid = review.run_id(result.to_dict())
    review.write_result(result.to_dict(), rid)
    st.session_state["rid"] = rid
else:
    result = st.session_state.get("result")
    rid = st.session_state.get("rid")
    if result is None:
        rid = rid or review.load_last_rid()
        if rid:
            result = review.load_result(rid)
        if result is None:
            st.stop()
        st.info("Showing results from the last run — re-run the backtest above to refresh.")

m = result.metrics

st.subheader("Metrics")
r1 = st.columns(4)
r1[0].metric("Total return", _fmt_pct(m.total_return))
r1[1].metric("CAGR", _fmt_pct(m.cagr))
r1[2].metric("Sharpe", _fmt_num(m.sharpe))
r1[3].metric("Sortino", _fmt_num(m.sortino))
r2 = st.columns(4)
r2[0].metric("Max drawdown", _fmt_pct(m.max_drawdown))
r2[1].metric("Win rate", _fmt_pct(m.win_rate))
r2[2].metric("Profit factor", _fmt_num(m.profit_factor))
r2[3].metric("Trades", m.num_trades)

st.subheader("Equity curve")
if result.equity_curve:
    st.plotly_chart(_equity_figure(result), use_container_width=True)
    st.metric("Max drawdown", _fmt_pct(m.max_drawdown))
else:
    st.warning("No equity curve — the backtest produced no trading bars.")

st.subheader("Trades")
trades = result.to_dict()["trades"]
if trades:
    st.dataframe(trades, use_container_width=True, hide_index=True)
else:
    st.caption("No trades in this run.")

# --- Claude review ---------------------------------------------------------

st.subheader("Claude review")
st.caption("On-demand only — runs Claude Code and spends tokens when you click.")
state = review.status(rid)
cols = st.columns([1, 1, 4])
if cols[0].button("Run Claude review", type="primary", disabled=not review.claude_available()):
    review.launch(rid)
    state = review.status(rid)
cols[1].button("Refresh")  # any interaction reruns the page and re-reads the file
if not review.claude_available():
    cols[2].caption("`claude` not on PATH — use the manual fallback below.")

if state.state == "done":
    st.markdown(review.read_review(rid))
elif state.state == "running":
    st.info("Review is running in Claude Code… click **Refresh** in a bit.")
elif state.state == "failed":
    st.error("Review failed. Log tail:")
    st.code(state.detail or "(no log)")
else:
    st.caption("No review yet.")

with st.expander("Run the review manually"):
    st.markdown(review.manual_instructions(rid))
