"""Hermes — a framework for developing, backtesting, and deploying intraday/swing
trading strategies on candlestick data.

See ``CONTEXT.md`` for the ubiquitous language and ``docs/adr/`` for the load-bearing
architectural decisions.

This module is the library's **map**: every name a strategy author or a research
agent needs is re-exported here, grouped by the same seams the package layout uses
(core / data / indicators / strategy / execution / ai / backtest). If a capability
exists in Hermes, it is importable from ``hermes`` directly — so
``python -c "import hermes; print(hermes.__all__)"`` is an honest inventory rather
than a subset. Sub-packages remain importable (``from hermes.backtest import ...``)
for anyone who prefers the narrower namespace.
"""

from __future__ import annotations

__version__ = "0.0.1"

from .ai import (
    AdvisorDecision,
    AIAdvisor,
    AIProvider,
    ClaudeProvider,
    ContextEnricher,
    DecisionCache,
    DeepSeekProvider,
    EDGARFilingEnricher,
    LLMCallRecord,
    LLMObservabilityLog,
    MassiveFundamentalsEnricher,
    MassiveFundamentalsScreen,
    PolygonNewsEnricher,
    RandomAdvisor,
    YFinanceFundamentalsEnricher,
    YFinanceFundamentalsScreen,
)
from .backtest import (
    DIVERSIFYING_BELOW,
    MIN_OVERLAP,
    REDUNDANT_ABOVE,
    TIER_CREDIBLE,
    TIER_DEPLOYABLE,
    TIER_EXPLORATORY,
    TIER_UNKNOWN,
    Backtest,
    BacktestResult,
    BatchResult,
    BenchmarkComparison,
    BenchmarkStats,
    ConfidenceInterval,
    CorrelationMatrix,
    Metrics,
    MetricsCI,
    MonteCarloStats,
    ParamCurve,
    ParamPoint,
    ParamSensitivity,
    PortfolioBacktest,
    PortfolioResult,
    RegimeAnalysis,
    RegimeStats,
    SampleQuality,
    StatValidation,
    UniverseBacktest,
    UniverseResult,
    WalkForward,
    WalkForwardResult,
    WalkForwardWindow,
    correlate_curves,
    correlate_results,
    cost_sensitivity,
    param_sensitivity,
    plot_equity,
    plot_trades,
    regime_analysis,
    run_batch,
    run_random_simulations,
    run_universe_random_simulations,
    split_isoos,
    tearsheet,
    validate,
)
from .core import (
    AssetClass,
    Bar,
    Cfd,
    CryptoPair,
    CryptoPerpetual,
    Instrument,
    PriceBasis,
    SessionCalendar,
    Stock,
    Symbol,
    Timeframe,
)
from .data import (
    BarCache,
    BinanceFuturesSource,
    BinanceSource,
    ConstituentCalendar,
    CTraderSource,
    DataSource,
    InMemorySource,
    MultiTimeframeView,
    PepperstoneSource,
    TiingoSource,
    TimeframeSeries,
    YFinanceSource,
)
from .data._ssl import ensure_system_trust as use_system_certs
from .execution import (
    Account,
    CommissionModel,
    CostModel,
    ExecutionVenue,
    FinancingModel,
    Liquidity,
    MakerTakerCommission,
    Order,
    OrderStatus,
    OrderType,
    PercentCommission,
    PerLotCommission,
    PerShareCommission,
    Position,
    Side,
    SimulatedVenue,
    SlippageModel,
    SpreadModel,
    Trade,
)
from .indicators import (
    ADX,
    ATR,
    EMA,
    FVG,
    MACD,
    RSI,
    SMA,
    BollingerBands,
    FairValueGap,
    Fractals,
    Indicator,
    LibraryIndicator,
)
from .research import (
    ALL_AXES,
    DEFAULT_AXES,
    SOURCES,
    STATUSES,
    Analysis,
    AxisResult,
    BrokenStrategy,
    Idea,
    IdeaBook,
    LedgerEntry,
    RestoredResult,
    ReviewStatus,
    RunLedger,
    RunMeta,
    RunRecord,
    StrategyEntry,
    analyze,
    build_source,
    cache_key,
    configured_backtest,
    declared_parameters,
    default_config,
    discover,
    discover_all,
    restore_result,
    run_universe,
    source_names,
    strategy_hash,
)
from .skilltools import install_skills
from .strategy import (
    EquityFraction,
    LeveragedFraction,
    NotionalCash,
    Parameter,
    Reference,
    RiskCash,
    RiskPercent,
    Sizer,
    SizingContext,
    Strategy,
    Units,
)

__all__ = [
    "__version__",
    # --- core: the vocabulary every other seam speaks ------------------------
    "Bar",
    "Timeframe",
    "Symbol",
    "Instrument",
    "Stock",
    "CryptoPair",
    "CryptoPerpetual",
    "Cfd",
    "AssetClass",
    "PriceBasis",
    "SessionCalendar",
    # --- data: market data in (the read half of the parity seam) -------------
    "DataSource",
    "YFinanceSource",
    "BinanceSource",
    "BinanceFuturesSource",
    "CTraderSource",
    "PepperstoneSource",
    "TiingoSource",
    "InMemorySource",
    "ConstituentCalendar",
    "BarCache",
    "MultiTimeframeView",
    "TimeframeSeries",
    # --- indicators ----------------------------------------------------------
    "Indicator",
    "LibraryIndicator",
    "SMA",
    "EMA",
    "RSI",
    "ATR",
    "MACD",
    "BollingerBands",
    "Fractals",
    "FairValueGap",
    "FVG",
    "ADX",
    # --- strategy: user-authored logic + its declared inputs -----------------
    "Strategy",
    "Parameter",
    "Reference",
    "Sizer",
    "SizingContext",
    "Units",
    "NotionalCash",
    "EquityFraction",
    "LeveragedFraction",
    "RiskCash",
    "RiskPercent",
    # --- execution: orders out (the write half of the parity seam) -----------
    "ExecutionVenue",
    "SimulatedVenue",
    "Order",
    "OrderType",
    "OrderStatus",
    "Side",
    "Trade",
    "Position",
    "Account",
    "Liquidity",
    "CostModel",
    "CommissionModel",
    "PercentCommission",
    "PerShareCommission",
    "PerLotCommission",
    "MakerTakerCommission",
    "SpreadModel",
    "SlippageModel",
    "FinancingModel",
    # --- ai: the optional confirm/veto gate ----------------------------------
    "AIAdvisor",
    "AIProvider",
    "AdvisorDecision",
    "ClaudeProvider",
    "DeepSeekProvider",
    "RandomAdvisor",
    "DecisionCache",
    "LLMCallRecord",
    "LLMObservabilityLog",
    "ContextEnricher",
    "YFinanceFundamentalsEnricher",
    "YFinanceFundamentalsScreen",
    "MassiveFundamentalsEnricher",
    "MassiveFundamentalsScreen",
    "EDGARFilingEnricher",
    "PolygonNewsEnricher",
    # --- backtest: running one ------------------------------------------------
    "Backtest",
    "BacktestResult",
    "Metrics",
    "BenchmarkComparison",
    "BenchmarkStats",
    # --- backtest: running many (the research primitives) --------------------
    "PortfolioBacktest",
    "PortfolioResult",
    "UniverseBacktest",
    "UniverseResult",
    "run_batch",
    "BatchResult",
    "WalkForward",
    "WalkForwardResult",
    "WalkForwardWindow",
    "split_isoos",
    "cost_sensitivity",
    "param_sensitivity",
    "ParamSensitivity",
    "ParamCurve",
    "ParamPoint",
    "correlate_curves",
    "correlate_results",
    "CorrelationMatrix",
    "REDUNDANT_ABOVE",
    "DIVERSIFYING_BELOW",
    "MIN_OVERLAP",
    "regime_analysis",
    "RegimeAnalysis",
    "RegimeStats",
    "run_random_simulations",
    "run_universe_random_simulations",
    # --- backtest: judging one ------------------------------------------------
    "validate",
    "StatValidation",
    "MetricsCI",
    "ConfidenceInterval",
    "MonteCarloStats",
    "SampleQuality",
    "TIER_EXPLORATORY",
    "TIER_CREDIBLE",
    "TIER_DEPLOYABLE",
    "TIER_UNKNOWN",
    # --- reporting ------------------------------------------------------------
    "plot_equity",
    "plot_trades",
    "tearsheet",
    # --- research loop: enumerate, record, judge (ADR-0010) -------------------
    "discover",
    "discover_all",
    "StrategyEntry",
    "BrokenStrategy",
    "default_config",
    "declared_parameters",
    "configured_backtest",
    "run_universe",
    "RunLedger",
    "RunMeta",
    "RunRecord",
    "LedgerEntry",
    "RestoredResult",
    "restore_result",
    "cache_key",
    "strategy_hash",
    "analyze",
    "Analysis",
    "AxisResult",
    "DEFAULT_AXES",
    "ALL_AXES",
    "ReviewStatus",
    "IdeaBook",
    "Idea",
    "SOURCES",
    "STATUSES",
    "build_source",
    "source_names",
    # --- tooling --------------------------------------------------------------
    "install_skills",
    "use_system_certs",
]
